# Generated by Django 6.0.5 on 2026-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Active', 'Active'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
